[display]
default_table_page_size = 20
cell_output = "below"
dataframes = "rich"
code_editor_font_size = 14
default_width = "medium"
theme = "light"
reference_highlighting = true

[snippets]
custom_paths = []
include_default_snippets = true

[diagnostics]

[experimental]

[language_servers.pylsp]
enable_pydocstyle = false
enabled = true
enable_flake8 = false
enable_pylint = false
enable_pyflakes = false
enable_ruff = true
enable_mypy = true

[save]
autosave_delay = 1000
autosave = "after_delay"
format_on_save = false

[runtime]
auto_reload = "off"
watcher_on_save = "lazy"
on_cell_change = "autorun"
auto_instantiate = true
reactive_tests = true
default_sql_output = "native"
output_max_bytes = 8000000
std_stream_max_bytes = 1000000

[keymap]
preset = "default"

[keymap.overrides]

[server]
follow_symlink = false
browser = "default"

[completion]
copilot = false
activate_on_typing = true

[package_management]
manager = "uv"

[ai]
mode = "manual"
rules = ""

[formatting]
line_length = 79
